### ISSUE TITLE
UnbufferedSelectSuite failed in Scala 2.11.x-jdk8 community build

### ISSUE THREAD

**Issue by SethTisue** [rssh/scala-gopher#12]
https://scala-ci.typesafe.com/job/scala-2.11.x-jdk8-integrate-community-build/261/consoleFull says:

```
[scala-gopher] [info] UnbufferedSelectSuite:
[scala-gopher] [info] - write without read must block 
[scala-gopher] [info] - fold over selector with one-direction flow *** FAILED ***
[scala-gopher] [info]   java.util.concurrent.TimeoutException: Futures timed out after [1 second]
[scala-gopher] [info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
[scala-gopher] [info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
[scala-gopher] [info]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[scala-gopher] [info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[scala-gopher] [info]   at scala.concurrent.package$.blocking(package.scala:123)
[scala-gopher] [info]   at scala.concurrent.Await$.result(package.scala:190)
[scala-gopher] [info]   at gopher.channels.UnbufferedSelectSuite$$anonfun$2$$anonfun$apply$mcV$sp$2.apply$mcVI$sp(UnbufferedSelectSuite.scala:55)
[scala-gopher] [info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
[scala-gopher] [info]   at gopher.channels.UnbufferedSelectSuite$$anonfun$2.apply$mcV$sp(UnbufferedSelectSuite.scala:45)
[scala-gopher] [info]   at gopher.channels.UnbufferedSelectSuite$$anonfun$2.apply(UnbufferedSelectSuite.scala:43)
[scala-gopher] [info]   ...
```

looks like another timeout that should be increased?

**Comment by rssh** [comment]
increased  (btw, looks like tests were restored during next ci run without my changes, but anyway ;))
