### ISSUE TITLE
intermittent IOTimeoutsSuite failure in Scala community build

### ISSUE THREAD

**Issue by SethTisue** [rssh/scala-gopher#17]
seen at https://scala-ci.typesafe.com/job/scala-2.11.x-integrate-community-build/392/consoleFull:

```
[scala-gopher] [info] IOTimeoutsSuite:
[scala-gopher] [info] - messsaged from timeouts must be appear during reading attempt from empty channel
[scala-gopher] [info] - when we have value, we have no timeouts
[scala-gopher] [info] - on input close it's timeout channel also must close
[scala-gopher] [info] - messsaged from timeouts must be appear during attempt to write to filled unbuffered channel
[scala-gopher] [info] - messsaged from timeouts must be appear during attempt to write to filled buffered channel *** FAILED ***
[scala-gopher] [info]   java.util.concurrent.TimeoutException: Futures timed out after [1 second]
[scala-gopher] [info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
[scala-gopher] [info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:157)
[scala-gopher] [info]   at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169)
[scala-gopher] [info]   at scala.concurrent.Await$$anonfun$ready$1.apply(package.scala:169)
[scala-gopher] [info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[scala-gopher] [info]   at scala.concurrent.package$.blocking(package.scala:123)
[scala-gopher] [info]   at scala.concurrent.Await$.ready(package.scala:169)
[scala-gopher] [info]   at gopher.channels.IOTimeoutsSuite$$anonfun$6.apply$mcV$sp(IOTimeoutsSuite.scala:102)
[scala-gopher] [info]   at gopher.channels.IOTimeoutsSuite$$anonfun$6.apply(IOTimeoutsSuite.scala:91)
[scala-gopher] [info]   at gopher.channels.IOTimeoutsSuite$$anonfun$6.apply(IOTimeoutsSuite.scala:91)
[scala-gopher] [info]   ...
[scala-gopher] [info] - when we have where to write -- no timeouts
[scala-gopher] [info] - on output close it's timeout channel also must close
[scala-gopher] [info] - during 'normal' processing timeouts are absent
```

maybe just a timeout that ought to be a bit longer...?

**Comment by rssh** [comment]
commit added => can close.
